"""empty message

Revision ID: 07f2ccca8bd0
Revises: 
Create Date: 2023-05-16 13:47:09.900646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07f2ccca8bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sailors')
    op.drop_table('reserves')
    op.drop_table('test')
    op.drop_table('boats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boats',
    sa.Column('bid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('bid'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('test',
    sa.Column('teststring', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('testint', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('testfloat', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('testint'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('reserves',
    sa.Column('sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('sid', 'bid', 'day'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('sailors',
    sa.Column('sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', mysql.FLOAT(precision=4, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###
