"""empty message

Revision ID: 448f7b84b017
Revises: 6ad892d9e4de
Create Date: 2023-05-29 20:30:24.806365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448f7b84b017'
down_revision = '6ad892d9e4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
