"""empty message

Revision ID: e31924d0ebbf
Revises: 
Create Date: 2023-05-12 23:13:08.839787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e31924d0ebbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boats')
    op.drop_table('test')
    op.drop_table('sailors')
    op.drop_table('reserves')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserves',
    sa.Column('sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('sid', 'bid', 'day'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('sailors',
    sa.Column('sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', mysql.FLOAT(precision=4, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('test',
    sa.Column('teststring', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('testint', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('testfloat', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('testint'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('boats',
    sa.Column('bid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bname', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('bid'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
